### ISSUE TITLE
POSIX shell checklist

### ISSUE THREAD

**Issue by xiaq** [elves/posixsh#1]
* [x] 2.2.1 Backslash escaping
* [x] 2.2.1 Line continuation
* [x] 2.2.2 Single quotes
* [x] 2.2.3 Double quotes
* [x] 2.3 Comment
  * 2.3.1 Alias substitution - test in `alias` instead
* [x] 2.5.1 Positional parameters
* [ ] 2.5.2 Special parameters
  * [x] `@`
  * [x] `*`
  * [x] `#`
  * [x] `?`
  * [x] `-`
  * [x] `$`
  * [ ] `!`
  * [x] `0`
* [ ] 2.5.3 Shell variables
  * [ ] `$ENV`
  * [x] `$HOME`
  * [x] `$IFS`
  * [x] ~`$LANG`, `$LC_*`, `$NLSPATH`~
  * [ ] `$LINENO`
  * [x] `$PATH`
  * [x] `$PPID`
  * [ ] `$PS1`
  * [ ] `$PS2`
  * [ ] `$PS4`
  * [x] `$PWD`
* [x] 2.6 Order of expansion
* [x] 2.6 Unparsed `$`
* [x] 2.6.1 Tilde expansion
* [x] 2.6.2 Parameter expansion
  * [x] `${parameter}`
  * [x] `${parameter:-[word]}`
  * [x] `${parameter:=[word]}`
  * [x] `${parameter:?[word]}`
  * [x] `${parameter:+[word]}`
  * [x] `${#parameter}`
  * [x] `${parameter:%[word]}`
  * [x] `${parameter:%%[word]}`
  * [x] `${parameter:#[word]}`
  * [x] `${parameter:##[word]}`
* [x] 2.6.3 Command substitution
* [x] 2.6.4 Arithmetic expansion
* [x] 2.6.5 Field splitting
* [x] 2.6.6 Pathname expansion
* [x] 2.6.7 Quote removal
* [x] 2.7.1 Redirecting input
* [x] 2.7.2 Redirecting output
* [x] 2.7.3 Appending redirected output
* [x] 2.7.4 Here-document
* [x] 2.7.5 Duplicating an input file descriptor
* [x] 2.7.6 Duplicating an output file descriptor
* [ ] 2.7.{5,6} Closing of file descriptor
* [x] 2.7.7 Open file descriptors for reading and writing
* [x] 2.8.1 Consequences of shell errors
* [x] 2.8.3 Exit status for commands
* [x] 2.9.1 Simple commands
* [ ] 2.9.1 Built-in commands
  * [x] `alias`
  * [ ] `bg`
  * [x] `cd`
  * [x] `command`
  * [x] `false`
  * [ ] `fc`
  * [ ] `fg`
  * [ ] `getopts`
  * [ ] `hash`
  * [ ] `jobs`
  * [x] ~`kill`~
  * [x] ~`newgrp`~
  * [x] `pwd`
  * [x] `read`
  * [x] `true`
  * [x] `type`
  * [x] `ulimit`
  * [x] `umask`
  * [x] `unalias`
  * [ ] `wait`
* [x] 2.9.2 Pipelines
* [x] 2.9.3 Lists (except async lists)
* [ ] 2.9.3 Async lists
* [x] 2.9.4 Compound commands
  * [x] `( )`
  * [x] `{ }`
  * [x] `for`
  * [x] `case`
  * [x] `if`
  * [x] `while`
  * [x] `until`
* [x] 2.9.5 Function definition commands
* [x] 2.10 Shell grammar
* [ ] 2.11 Signals and error handling
* [ ] 2.12 Shell execution environment
* [x] 2.13 Pattern matching notation
* [ ] 2.14 Special built-in utilities
  * [x] `break`
  * [x] `:`
  * [x] `continue`
  * [x] `.`
  * [x] `eval`
  * [ ] `exec`
  * [x] `exit`
  * [x] `export`
  * [x] `readonly`
  * [x] `return`
  * [x] `set`
  * [x] `shift`
  * [x] `times`
  * [ ] `trap`
  * [x] `unset`
* Options
  * [x] `allexport`
  * [ ] `errexit`
  * [x] ~`ignoreeof`~
  * [ ] `monitor`
  * [x] `noclobber`
  * [x] `noglob`
  * [ ] `noexec`
  * [x] ~`nolog`~
  * [ ] `notify`
  * [x] `nounset`
  * [x] `verbose`
  * [x] `xtrace`
  * [x] ~`-h`~
